package ece358;
// Generated 14-Mar-2014 5:41:19 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Operations generated by hbm2java
 */
public class Operations  implements java.io.Serializable {


     private String name;
     private String description;
     private Date estTime;
     private String reqJobTitle;

    public Operations() {
    }

	
    public Operations(String name) {
        this.name = name;
    }
    public Operations(String name, String description, Date estTime, String reqJobTitle) {
       this.name = name;
       this.description = description;
       this.estTime = estTime;
       this.reqJobTitle = reqJobTitle;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getEstTime() {
        return this.estTime;
    }
    
    public void setEstTime(Date estTime) {
        this.estTime = estTime;
    }
    public String getReqJobTitle() {
        return this.reqJobTitle;
    }
    
    public void setReqJobTitle(String reqJobTitle) {
        this.reqJobTitle = reqJobTitle;
    }




}


