package ece358;
// Generated 14-Mar-2014 5:41:19 PM by Hibernate Tools 3.6.0



/**
 * Patients generated by hbm2java
 */
public class Patients  implements java.io.Serializable {


     private String userId;
     private String firstName;
     private String lastName;
     private String address;
     private String phoneNumber;
     private String email;
     private String healthCardNumber;
     private String sin;
     private Integer visits;
     private String defaultDoctorId;
     private String healthStatus;
     private String primaryContractNo;
     private Boolean transfered;

    public Patients() {
    }

	
    public Patients(String userId) {
        this.userId = userId;
    }
    public Patients(String userId, String firstName, String lastName, String address, String phoneNumber, String email, String healthCardNumber, String sin, Integer visits, String defaultDoctorId, String healthStatus, String primaryContractNo, Boolean transfered) {
       this.userId = userId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.healthCardNumber = healthCardNumber;
       this.sin = sin;
       this.visits = visits;
       this.defaultDoctorId = defaultDoctorId;
       this.healthStatus = healthStatus;
       this.primaryContractNo = primaryContractNo;
       this.transfered = transfered;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getHealthCardNumber() {
        return this.healthCardNumber;
    }
    
    public void setHealthCardNumber(String healthCardNumber) {
        this.healthCardNumber = healthCardNumber;
    }
    public String getSin() {
        return this.sin;
    }
    
    public void setSin(String sin) {
        this.sin = sin;
    }
    public Integer getVisits() {
        return this.visits;
    }
    
    public void setVisits(Integer visits) {
        this.visits = visits;
    }
    public String getDefaultDoctorId() {
        return this.defaultDoctorId;
    }
    
    public void setDefaultDoctorId(String defaultDoctorId) {
        this.defaultDoctorId = defaultDoctorId;
    }
    public String getHealthStatus() {
        return this.healthStatus;
    }
    
    public void setHealthStatus(String healthStatus) {
        this.healthStatus = healthStatus;
    }
    public String getPrimaryContractNo() {
        return this.primaryContractNo;
    }
    
    public void setPrimaryContractNo(String primaryContractNo) {
        this.primaryContractNo = primaryContractNo;
    }
    public Boolean getTransfered() {
        return this.transfered;
    }
    
    public void setTransfered(Boolean transfered) {
        this.transfered = transfered;
    }




}


