package ece358;
// Generated 14-Mar-2014 5:41:19 PM by Hibernate Tools 3.6.0



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String userId;
     private String password;
     private String role;

    public Users() {
    }

    public Users(String userId, String password, String role) {
       this.userId = userId;
       this.password = password;
       this.role = role;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


