package ece358.models;
// Generated Mar 17, 2014 7:33:52 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Doctorpatientperm generated by hbm2java
 */
public class Doctorpatientperm  implements java.io.Serializable {


     private String patientId;
     private String doctorId;
     private String secDoctorId;
     private Date expiry;

    public Doctorpatientperm() {
    }

	
    public Doctorpatientperm(String patientId, String doctorId, String secDoctorId) {
        this.patientId = patientId;
        this.doctorId = doctorId;
        this.secDoctorId = secDoctorId;
    }
    public Doctorpatientperm(String patientId, String doctorId, String secDoctorId, Date expiry) {
       this.patientId = patientId;
       this.doctorId = doctorId;
       this.secDoctorId = secDoctorId;
       this.expiry = expiry;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }
    public String getSecDoctorId() {
        return this.secDoctorId;
    }
    
    public void setSecDoctorId(String secDoctorId) {
        this.secDoctorId = secDoctorId;
    }
    public Date getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(Date expiry) {
        this.expiry = expiry;
    }




}


