package ece358.models;
// Generated Mar 17, 2014 7:33:52 PM by Hibernate Tools 3.6.0


import ece358.models.mapping.MySQLObjectMapping;
import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Operations generated by hbm2java
 */
public class Operations  implements MySQLObjectMapping {

     public String name;
     public String description;
     public Date estTime;
     public String reqJobTitle;

    public Operations() {
    }

    public Operations(String name) {
        this.name = name;
    }

    public Operations(String name, String description, Date estTime, String reqJobTitle) {
       this.name = name;
       this.description = description;
       this.estTime = estTime;
       this.reqJobTitle = reqJobTitle;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public Date getEstTime() {
        return this.estTime;
    }
    
    public void setEstTime(Date estTime) {
        this.estTime = estTime;
    }
    public String getReqJobTitle() {
        return this.reqJobTitle;
    }
    
    public void setReqJobTitle(String reqJobTitle) {
        this.reqJobTitle = reqJobTitle;
    }

    @Override
    public List<Field> getIdFields() {
        return new ArrayList<Field>(){{
            add(Drugs.class.getDeclaredFields()[0]);
        }};
    }
    
    @Override
    public boolean equals(Object other) {
        if (other != null && other instanceof Operations) {
            return ((Operations) other).getName().equals(this.getName());
        }
        return false;
    }
}


