package ece358.models;
// Generated Mar 17, 2014 4:52:23 PM by Hibernate Tools 3.6.0



/**
 * Patients generated by hbm2java
 */
public class Patients  implements java.io.Serializable {


     private String userId;
     private String firstName;
     private String lastName;
     private String address;
     private String city;
     private String province;
     private String country;
     private String postalCode;
     private String phoneNumber;
     private String email;
     private String healthCardNumber;
     private String sin;
     private Integer visits;
     private String defaultDoctorId;
     private String healthStatus;
     private String primaryContactNo;
     private Boolean transfered;

    public Patients() {
    }

	
    public Patients(String userId) {
        this.userId = userId;
    }
    public Patients(String userId, String firstName, String lastName, String address, String city, String province, String country, String postalCode, String phoneNumber, String email, String healthCardNumber, String sin, Integer visits, String defaultDoctorId, String healthStatus, String primaryContactNo, Boolean transfered) {
       this.userId = userId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.city = city;
       this.province = province;
       this.country = country;
       this.postalCode = postalCode;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.healthCardNumber = healthCardNumber;
       this.sin = sin;
       this.visits = visits;
       this.defaultDoctorId = defaultDoctorId;
       this.healthStatus = healthStatus;
       this.primaryContactNo = primaryContactNo;
       this.transfered = transfered;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getHealthCardNumber() {
        return this.healthCardNumber;
    }
    
    public void setHealthCardNumber(String healthCardNumber) {
        this.healthCardNumber = healthCardNumber;
    }
    public String getSin() {
        return this.sin;
    }
    
    public void setSin(String sin) {
        this.sin = sin;
    }
    public Integer getVisits() {
        return this.visits;
    }
    
    public void setVisits(Integer visits) {
        this.visits = visits;
    }
    public String getDefaultDoctorId() {
        return this.defaultDoctorId;
    }
    
    public void setDefaultDoctorId(String defaultDoctorId) {
        this.defaultDoctorId = defaultDoctorId;
    }
    public String getHealthStatus() {
        return this.healthStatus;
    }
    
    public void setHealthStatus(String healthStatus) {
        this.healthStatus = healthStatus;
    }
    public String getPrimaryContactNo() {
        return this.primaryContactNo;
    }
    
    public void setPrimaryContactNo(String primaryContactNo) {
        this.primaryContactNo = primaryContactNo;
    }
    public Boolean getTransfered() {
        return this.transfered;
    }
    
    public void setTransfered(Boolean transfered) {
        this.transfered = transfered;
    }




}


