package ece358.models;
// Generated Mar 16, 2014 5:46:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Prescriptions generated by hbm2java
 */
public class Prescriptions  implements java.io.Serializable {


     private PrescriptionsId id;
     private Integer quantity;
     private Integer refills;
     private String dosage;
     private Date expiry;

    public Prescriptions() {
    }

	
    public Prescriptions(PrescriptionsId id) {
        this.id = id;
    }
    public Prescriptions(PrescriptionsId id, Integer quantity, Integer refills, String dosage, Date expiry) {
       this.id = id;
       this.quantity = quantity;
       this.refills = refills;
       this.dosage = dosage;
       this.expiry = expiry;
    }
   
    public PrescriptionsId getId() {
        return this.id;
    }
    
    public void setId(PrescriptionsId id) {
        this.id = id;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getRefills() {
        return this.refills;
    }
    
    public void setRefills(Integer refills) {
        this.refills = refills;
    }
    public String getDosage() {
        return this.dosage;
    }
    
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }
    public Date getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(Date expiry) {
        this.expiry = expiry;
    }




}


