package ece358.models;
// Generated Mar 17, 2014 7:33:52 PM by Hibernate Tools 3.6.0



/**
 * Scheduledoperations generated by hbm2java
 */
public class Scheduledoperations  implements java.io.Serializable {


     private ScheduledoperationsId id;
     private String operationName;
     private String doctorId;

    public Scheduledoperations() {
    }

	
    public Scheduledoperations(ScheduledoperationsId id, String doctorId) {
        this.id = id;
        this.doctorId = doctorId;
    }
    public Scheduledoperations(ScheduledoperationsId id, String operationName, String doctorId) {
       this.id = id;
       this.operationName = operationName;
       this.doctorId = doctorId;
    }
   
    public ScheduledoperationsId getId() {
        return this.id;
    }
    
    public void setId(ScheduledoperationsId id) {
        this.id = id;
    }
    public String getOperationName() {
        return this.operationName;
    }
    
    public void setOperationName(String operationName) {
        this.operationName = operationName;
    }
    public String getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }




}


