package ece358.models;
// Generated Mar 17, 2014 7:33:52 PM by Hibernate Tools 3.6.0

import ece358.models.mapping.MySQLObjectMapping;
import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;




/**
 * Users generated by hbm2java
 */
public class Users  implements MySQLObjectMapping {
     public String userId;
     public String password;
     public String role;

    public Users() {
    }

    public Users(String userId, String password, String role) {
       this.userId = userId;
       this.password = password;
       this.role = role;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public List<Field> getIdFields() {
       return new ArrayList<Field>(){{
            add(Users.class.getDeclaredFields()[0]);
        }};
    }
}


