package ece358.models;
// Generated Mar 16, 2014 12:26:23 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Visitation generated by hbm2java
 */
public class Visitation  implements java.io.Serializable {


     private int recordId;
     private Date timestamp;
     private int visitId;
     private String patientId;
     private String doctorId;
     private String symptoms;
     private String diagnosis;
     private String type;
     private Date length;
     private String comments;
     private Date dateTime;
     private Boolean apptComplete;
     private Boolean cancelled;

    public Visitation() {
    }

	
    public Visitation(int recordId, int visitId, String patientId, String doctorId) {
        this.recordId = recordId;
        this.visitId = visitId;
        this.patientId = patientId;
        this.doctorId = doctorId;
    }
    public Visitation(int recordId, int visitId, String patientId, String doctorId, String symptoms, String diagnosis, String type, Date length, String comments, Date dateTime, Boolean apptComplete, Boolean cancelled) {
       this.recordId = recordId;
       this.visitId = visitId;
       this.patientId = patientId;
       this.doctorId = doctorId;
       this.symptoms = symptoms;
       this.diagnosis = diagnosis;
       this.type = type;
       this.length = length;
       this.comments = comments;
       this.dateTime = dateTime;
       this.apptComplete = apptComplete;
       this.cancelled = cancelled;
    }
   
    public int getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(int recordId) {
        this.recordId = recordId;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public int getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(int visitId) {
        this.visitId = visitId;
    }
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public String getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }
    public String getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }
    public String getDiagnosis() {
        return this.diagnosis;
    }
    
    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getLength() {
        return this.length;
    }
    
    public void setLength(Date length) {
        this.length = length;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Boolean getApptComplete() {
        return this.apptComplete;
    }
    
    public void setApptComplete(Boolean apptComplete) {
        this.apptComplete = apptComplete;
    }
    public Boolean getCancelled() {
        return this.cancelled;
    }
    
    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }




}


