package ece358.models;
// Generated Mar 17, 2014 7:33:52 PM by Hibernate Tools 3.6.0


import ece358.models.mapping.MySQLObjectMapping;
import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Visitation generated by hbm2java
 */
public class Visitation  implements MySQLObjectMapping {
     public Integer recordId;
     public Integer visitId;
     public String patientId;
     public String doctorId;
     public String symptoms;
     public String diagnosis;
     public String type;
     public Time length;
     public String comments;
     public Date dateTime;
     public Date timestamp;
     public Boolean apptComplete;
     public Boolean cancelled;
     
     // Custom object
     private List<Object[]> prescriptions;
     private List<Scheduledoperations> operations;

    public Visitation() {
    }

    public Visitation(int recordId, int visitId, String patientId, String doctorId) {
        this.recordId = recordId;
        this.visitId = visitId;
        this.patientId = patientId;
        this.doctorId = doctorId;
    }
    public Visitation(int recordId, int visitId, String patientId, String doctorId, String symptoms, String diagnosis, String type, Time length, String comments, Date dateTime, Boolean apptComplete, Boolean cancelled) {
       this.recordId = recordId;
       this.visitId = visitId;
       this.patientId = patientId;
       this.doctorId = doctorId;
       this.symptoms = symptoms;
       this.diagnosis = diagnosis;
       this.type = type;
       this.length = length;
       this.comments = comments;
       this.dateTime = dateTime;
       this.apptComplete = apptComplete;
       this.cancelled = cancelled;
    }

    public int getRecordId() {
        return this.recordId;
    }

    public void setRecordId(int recordId) {
        this.recordId = recordId;
    }

    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public int getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(int visitId) {
        this.visitId = visitId;
    }

    public String getPatientId() {
        return this.patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getDoctorId() {
        return this.doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public String getSymptoms() {
        return this.symptoms;
    }

    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }

    public String getDiagnosis() {
        return this.diagnosis;
    }

    public void setDiagnosis(String diagnosis) {
        this.diagnosis = diagnosis;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Time getLength() {
        return this.length;
    }

    public void setLength(Time length) {
        this.length = length;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public Date getDateTime() {
        return this.dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    public Boolean getApptComplete() {
        return this.apptComplete;
    }

    public void setApptComplete(Boolean apptComplete) {
        this.apptComplete = apptComplete;
    }

    public Boolean getCancelled() {
        return this.cancelled;
    }

    public void setCancelled(Boolean cancelled) {
        this.cancelled = cancelled;
    }

    public List<Object[]> getPrescriptions() {
        return this.prescriptions;
    }

    public void setPrescriptions(List<Object[]> prescriptions) {
        this.prescriptions = prescriptions;
    }

    public List<Scheduledoperations> getOperations() {
        return this.operations;
    }

    public void setOperations(List<Scheduledoperations> operations) {
        this.operations = operations;
    }

    @Override
    public List<Field> getIdFields() {
        return new ArrayList<Field>(){{
            add(Users.class.getDeclaredFields()[0]);
        }};
    }
}


